### ISSUE TITLE
Add PeekingTakeWhile iterator

### ISSUE THREAD

**Issue by foresterre** [foresterre/peekmore#34]
Similar to [iter::TakeWhile](https://doc.rust-lang.org/std/iter/struct.TakeWhile.html), but the predicate is checked against the next peek() value instead of the consumed value

**Comment by pickfire** [comment]
This is available to in both `peeking_take_while` and `itertools` crate.

**Comment by foresterre** [comment]
@pickfire Thanks for informing me about these crates 😄; I probably should have looked before making a new issue. `peeking_take_while` seems to be what I needed. I really like `itertools` in general but sometimes you want something a bit more lightweight; and then pulling in itertools isn't always the prefered choice.

Anyways, thanks again!

**Comment by pickfire** [comment]
@foresterre Note that `itertools` only depends on `iter`. I would say it is still quite lightweight but comprehensive.

**Comment by foresterre** [comment]
Yes! I meant that it contains a lot more than I usually need :).
