### ISSUE TITLE
Add the ability to move iterator to current cursor position

### ISSUE THREAD

**Issue by connorskees** [foresterre/peekmore#35]
Hello,

In using this library for parsing Sass, I am finding that I have to pass around and add together `usize`s in order to keep track of how far I have peeked.

In order to parse Sass, oftentimes it is necessary to attempt to parse something and then backtrack if that parsing failed.

For example, when attempting to parse `url`, my code looks something like

```rust
if let Some((value, peek_length)) = self.try_parse_url() {
  self.toks.take(peek_length).for_each(drop);
  return Ok(value);
} else {
  self.toks.reset_view();
}
```

Manually keeping track of the peeklength is tedious and prone to error. Within `try_parse_url()`, there is a lot of additional logic for keeping track of the current position.

For example, in this branch that parses interpolation, manually keeping track of the position adds a lot of unnecessary noise and comes with the caveat that forgetting to add even one token to the `peek_counter` would break parsing. 
```rust
if let Some(Token { kind: '{', .. }) = self.toks.peek() {
    self.toks.advance_cursor();
    peek_counter += 1;
    let (interpolation, count) = self.peek_interpolation()?;
    peek_counter += count;
    buf.push_str(&interpolation);
} else {
    buf.push('#');
}
```

Adding a method like `move_iterator_to_cursor()` (hopefully we can come up with a better name) would allow me to significantly simplify these two examples,
```rust
if let Some(value) = self.try_parse_url() {
  self.toks.move_iterator_to_cursor();
  return Ok(value);
} else {
  self.toks.reset_view();
}
```
```rust
if let Some(Token { kind: '{', .. }) = self.toks.peek() {
    self.toks.advance_cursor();
    buf.push_str(&self.peek_interpolation()?);
} else {
    buf.push('#');
}
```

**Comment by foresterre** [comment]
Hi, Thank you for the extensive description of your problem statement, use case and request. I think this would make for a fine addition. I'll review your PR soon!

**Comment by foresterre** [comment]
Published on crates.io ([v0.5.2](https://crates.io/crates/peekmore/0.5.2))
