### ISSUE TITLE
`truncate_iterator_to_cursor` does not respect `advance_cursor`

### ISSUE THREAD

**Issue by connorskees** [foresterre/peekmore#38]
Hello,

It seems my implementation of `truncate_iterator_to_cursor` did not take into account `advance_cursor`'s lack of filling the queue. A minimal reproduction for this issue is below,
```rust
use peekmore::PeekMore;

fn main() {
    let mut iter = [0, 1, 2, 3].iter().peekmore();
    iter.advance_cursor();
    iter.truncate_iterator_to_cursor();
    dbg!(iter.peek());
}
```

This will print `0`, though the expected result is `1`. Replacing `iter.advance_cursor();` with `iter.peek_next();` results in the expected output.

**Comment by foresterre** [comment]
Hi 👋. Thanks for the clear report. Do you want to make a PR yourself, or shall I?

**Comment by foresterre** [comment]
@connorskees I think it should be fixed now; could you perhaps try it out and see if it works for you?

**Comment by connorskees** [comment]
Hi! Thank you so much for the fix -- I got a bit preoccupied.

Unfortunately it appears that this has resulted in a different bug.

I have minized the case to
```rust
use peekmore::PeekMore;

fn main() {
    let mut iter = [0, 1, 2, 3].iter().peekmore();
    iter.peek();
    iter.advance_cursor();
    iter.truncate_iterator_to_cursor();
    dbg!(iter);
}
```

This will print out
```rust
[src\main.rs:9] iter = PeekMoreIterator {
    iterator: Iter(
        [
            2,
            3,
        ],
    ),
    queue: [
        Some(
            0,
        ),
    ],
    cursor: 0,
}
```
where ideally the `1` value would still be in the iterator or queue. I suppose here `for _ in 0..self.cursor`, rather than `self.cursor`, it should be something like `self.cursor - self.queue.len()`?

**Comment by foresterre** [comment]
Good catch!
